services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    command: ./docker-entrypoint.sh
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
